[project]
name = "weather-fastapi-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.14.*"

dependencies = [
    "fastapi[standard]>=0.121.1",
    "uvicorn>=0.38.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.0",
]

